---
- name: Create otelcol config directory
  file:
    path: "{{ otel_config_path | dirname }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy otelcol configuration
  template:
    src: config.yaml.j2
    dest: "{{ otel_config_path }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart otelcol
