---
- name: restart victoriametrics
  ansible.builtin.systemd:
    name: victoriametrics
    state: restarted
    daemon_reload: true

- name: restart victorialogs
  ansible.builtin.systemd:
    name: victorialogs
    state: restarted
    daemon_reload: true
