- name: Import install tasks
  ansible.builtin.import_tasks: install.yml

- name: Import config tasks
  ansible.builtin.import_tasks: config.yml

- name: Import service tasks
  ansible.builtin.import_tasks: service.yml
